ExploreCalifornia/Models/BlogDataContext.cs
using Microsoft.EntityFrameworkCore;

namespace ExploreCalifornia.Models;

public sealed class BlogDataContext : DbContext
{
    public DbSet<Post> Posts { get; set; }

    public BlogDataContext(DbContextOptions<BlogDataContext> options) : base(options)
    {
        Database.EnsureCreated();
    }
    
    public IQueryable<MonthlySpecial> MonthlySpecials
    {
        get
        {
            return new[]
            {
                new MonthlySpecial {
                    Key = "calm",
                    Name = "California Calm Package",
                    Type = "Day Spa Package",
                    Price = 250,
                },
                new MonthlySpecial {
                    Key = "desert",
                    Name = "From Desert to Sea",
                    Type = "2 Day Salton Sea",
                    Price = 350,
                },
                new MonthlySpecial {
                    Key = "backpack",
                    Name = "Backpack Cali",
                    Type = "Big Sur Retreat",
                    Price = 620,
                },
                new MonthlySpecial {
                    Key = "taste",
                    Name = "Taste of California",
                    Type = "Tapas & Groves",
                    Price = 150,
                },
            }.AsQueryable();
        }
    }
}

ExploreCalifornia/Models/FormattingService.cs
namespace ExploreCalifornia.Models;

public class FormattingService
{
    public string AsFormattedDate(DateTime dateTime)
    {
        return dateTime.ToString("d");
    }
}

ExploreCalifornia/Models/MonthlySpecial.cs
namespace ExploreCalifornia.Models
{
    public class MonthlySpecial
    {
        public string Key { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int Price { get; set; }
    }
}

ExploreCalifornia/Models/Post.cs
using System.ComponentModel.DataAnnotations;
using System.Text.RegularExpressions;

namespace ExploreCalifornia.Models;

public class Post
{

    public long Id { get; set; }
    
    [Required]
    [Display(Name = "Post Title")]
    [StringLength(100, MinimumLength = 5, ErrorMessage = "Title must be between 5 and 500 chars")]
    public string Title { get; set; }
    public string? Author { get; set; }
    
    [Required]
    [MinLength(100, ErrorMessage = "Blog posts must be at least 100 chars")]
    [DataType(DataType.MultilineText)]
    public string Body { get; set; }
    public DateTime Posted { get; set; }
    
}

ExploreCalifornia/Controllers/BlogController.cs
using ExploreCalifornia.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExploreCalifornia.Controllers;

[Route("blog")]
public class BlogController : Controller
{
    private readonly BlogDataContext _db;

    public BlogController(BlogDataContext db)
    {
        _db = db;
    }
    public IActionResult Index(int page = 0)
    {
        var pageSize = 2;
        var totalPosts = _db.Posts.Count();
        var totalPages = totalPosts / pageSize;
        var previousPage = page - 1;
        var nextPage = page + 1;

        ViewBag.PreviousPage = previousPage;
        ViewBag.HasPreviousPage = previousPage >= 0;
        ViewBag.NextPage = nextPage;
        ViewBag.HasNextPage = nextPage < totalPages;
        
        var posts = _db.Posts
            .OrderByDescending(x => x.Posted)
            .Skip(pageSize * page)
            .Take(pageSize)
            .ToArray();
        return View(posts);
    }

    [Route("{year:min(2000)}/{month:range(1,12)}/{id}")]
    public IActionResult Post(int year, int month, int id)
    {
        var post = _db.Posts.FirstOrDefault(x => x.Id == id);
        // ViewBag.Title = "My blog post";
        // ViewBag.Posted = DateTime.Now;
        // ViewBag.Author = "Chris Elbert";
        // ViewBag.Body = "This is a great blog post, don't you think?";
        return View(post);
    }

    [Route("create")]
    [HttpGet]
    public IActionResult Create()
    {
        return View();
    }
    
    [Route("create")]
    [HttpPost]
    public IActionResult Create(Post post)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }
        
        post.Author = User.Identity.Name ?? "Default";
        post.Posted = DateTime.Now;

        _db.Posts.Add(post);
        _db.SaveChanges();

        return RedirectToAction("Post", "Blog", new
        {
            year = post.Posted.Year,
            month = post.Posted.Month,
            id = post.Id
        });
    }
}

ExploreCalifornia/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ExploreCalifornia.Controllers;

public class HomeController : Controller
{
    // GET
    public IActionResult Index()
    {
        return View();
    }
}

ExploreCalifornia/ViewComponents/MonthlySpecialsViewComponent.cs
using ExploreCalifornia.Models;
using Microsoft.AspNetCore.Mvc;

namespace ExploreCalifornia.ViewComponents;

public class MonthlySpecialsViewComponent : ViewComponent
{
    private readonly BlogDataContext _db;
    public MonthlySpecialsViewComponent(BlogDataContext db)
    {
        _db = db;
    }
    public IViewComponentResult Invoke()
    {
        var specials = _db.MonthlySpecials.ToArray();
        return View(specials);
    }
}

ExploreCalifornia/Views/Blog/Create.cshtml
@addTagHelper "*, Microsoft.AspNetCore.Mvc.TagHelpers"
@model ExploreCalifornia.Models.Post

@{
    Layout = "_Layout";
}

<h1>Create Blog Post</h1>

<fieldset>
    <form asp-action="Create" asp-controller="Blog">
        <div asp-validation-summary="ModelOnly" class="input-validation-error"></div>
        <p>
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" placeholder="Blog Post Title"/>
            <span asp-validation-for="Title"></span>
        </p>
        <p>
            <label asp-for="Body"></label>
            <textarea asp-for="Body" class="form-control" placeholder="Blog Post Content"></textarea>
            <span asp-validation-for="Body"></span>
        </p>
        <p>
            <button type="submit">Create Post</button>
        </p>
    </form>
</fieldset>

ExploreCalifornia/Views/Blog/index.cshtml
@model ExploreCalifornia.Models.Post[]

@{
    Layout = "_Layout";
}

<h1>Explorer's Blog</h1>

<p>
    Below are a few of the latest posts from some of our explorers.
</p>

<p class="pager">
    @if (ViewBag.HasPreviousPage)
    {
        <a class="prev" href="@Url.Action("Index", "Blog", new { page = ViewBag.PreviousPage })">
            &lt; Previous
        </a>
    }
    
    @if (ViewBag.HasNextPage)
    {
        <a class="next" href="@Url.Action("Index", "Blog", new { page = ViewBag.NextPage })">
            Next &gt;
        </a>
    }
</p>

<div class="blog-posts">
    @foreach (var post in Model)
    {
        @await Html.PartialAsync("_Post", post);
    }
</div>

ExploreCalifornia/Views/Blog/post.cshtml
@model ExploreCalifornia.Models.Post

@{
    Layout = "_Layout";
}

@await Html.PartialAsync("_Post")

ExploreCalifornia/Views/Home/index.cshtml
@{
    Layout = "_Layout";
}

@section header
{
    <h1>Explore our world your way</h1>
    <a href="/tours.htm" title="Find your tour!"><h2>Find your tour</h2></a>
}

<article id="mainArticle"> 
    <h1>Tour Spotlight</h1>
    <p class="spotlight">This month's spotlight package is Cycle California. Whether you are looking for some serious downhill thrills to a relaxing ride along the coast, you'll find something to love in Cycle California.<br /> <span class="accent"><a href="/tours_cycle.htm" title="Cycle California">tour details</a></span></p>
    <h1>Explorer's Podcast</h1>
    <video controls poster="/images/podcast_poster.jpg" width="512" height="288" preload="none">
        <source src="_video/podcast_teaser.mp4" type="video/mp4" />
        <source src="_video/podcast_teaser.webm" type="video/webm" />
        <source src="_video/podcast_teaser.theora.ogv"type="video/ogg" />
    </video>
    <p class="videoText">Join us each month as we publish a new Explore California video podcast, with featured tours, customer photos, and some exctiing new features!<span class="accent"><a href="explorers/video.htm" title="Video Podcast">Watch the full video</a></span></p>
</article>

ExploreCalifornia/Views/Shared/Components/MonthlySpecials/Default.cshtml
@model IEnumerable<ExploreCalifornia.Models.MonthlySpecial>

<h1>Monthly Specials</h1>

@foreach (var special in Model)
{
    <h2 class="top">
        <img src="/images/@(special.Key)_bug.gif" alt="@special.Name" width="75" height="75"/>
        @special.Name
    </h2>
    <p>
        @special.Type <br/>
        <a href="/tours/@(special.Key).htm">$@special.Price</a>
    </p>
}

ExploreCalifornia/Views/Shared/_Layout.cshtml
@addTagHelper *, ExploreCalifornia
<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Welcome to Explore California</title>
<meta name="description" content="A lynda.com example of HTML5 and CSS3">
<meta name="keywords" content="html5, css3, lynda, local storage, canvas, forms, semantics, web apps">
<!--make sure mobile devices display the page at the proper scale	-->
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<link href="/css/main.css" rel="stylesheet" type="text/css" media="screen, projection">
</head>
<body id="home" class="no-js">
<div id="wrapper">
  <header id="mainHeader"> <a href="/" title="home" class="logo">
   <!-- I need this div because IE is an affront to mankind-->
    <div>
    <h1>Explore California</h1>
    </div>
    </a>
    <nav id="siteNav">
      <h1>Where do you want to go?</h1>
      <ul>
       <li><a href="/tours.htm" title="Our tours">Tours <br /><span class="tagline">follow our bliss</span></a>
          <ul>
            <li><a href="/tours.htm" title="Our tours">All Tours</a></li>
            <li><a href="/tours.htm" title="find tours">Tours by Activity</a></li>
            <li><a href="/tours.htm" title="find tours">Tours by Region</a></li>
            <li><a href="/tours.htm" title="find tours">Tour Finder</a></li>
          </ul>
        </li>
        <li><a href="mission.htm" title="What we believe">Mission <br /><span class="tagline">what makes us different?</span></a></li>
        <li><a href="resources.htm" title="planning resources">Resources <br /><span class="tagline">plan your trip</span></a>
          <ul>
            <li><a href="resources/faq.htm" title="Got questions?">Tour FAQs</a></li>
            <li><a href="resources/additional_resources.htm" title="additional resources">Tour Information</a></li>
            <li><a href="resources/terms.htm" title="terms and conditions">Site Terms</a></li>
          </ul>
        </li>
        <li><a href="explorers.htm" title="Our community">Explorers <br /><span class="tagline">join our community</span></a>
          <ul>
            <li><a href="@Url.Action("Index", "Blog")" title="read our blog! :)">Read our Blog</a></li>
            <li><a href="explorers/gallery.htm" title="contributor photos">Tour Photos</a></li>
            <li><a href="_video/EC_podcast_full version.mov" title="check out our podcast">Video podcast</a></li>
          </ul>
        </li>
        <li><a href="contact.htm" title="contact us" class="last">Contact <br /><span class="tagline">we're listening</span></a>
          <ul>
            <li><a href="support.htm" title="need help?">Support</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </header>
  <section id="actionCall">
    @if (IsSectionDefined("header"))
    {
      @await RenderSectionAsync("header", false)
    }
  </section>
  <div id="contentWrapper">
    <section id="mainContent">
      @RenderBody()
    </section>
    <aside id="secondaryContent">
      <div id="specials" class="callOut">
        <vc:monthly-specials />
        @* <h1>Monthly Specials</h1> *@
        @* <h2 class="top"><img src="/images/calm_bug.gif" alt="California Calm" width="75" height="75">California Calm</h2> *@
        @* <p> *@
        @*     Day Spa Package <br> *@
        @*     <a href="/tours/tour_detail_cycle.htm">$250</a> *@
        @* </p> *@
        @* <h2><img src="/images/desert_bug.gif" alt="From desert to sea" width="75" height="75">From Desert to Sea</h2> *@
        @* <p> *@
        @*     2 Day Salton Sea <br> *@
        @*     <a href="/tours/tour_detail_cycle.htm">$350</a> *@
        @* </p> *@
        @* <h2><img src="/images/backpack_bug.gif" alt="Backpack Cali" width="75" height="41">Backpack Cali</h2> *@
        @* <p> *@
        @*     Big Sur Retreat <br> *@
        @*     <a href="/tours/tour_detail_cycle.htm">$620</a> *@
        @* </p> *@
        @* <h2><img src="/images/taste_bug.gif" alt="Taste of California" width="75" height="75">Taste of California</h2> *@
        @* <p> *@
        @*     Tapas &amp; Groves <br> *@
        @*     <a href="/tours/tour_detail_taste.htm">$150</a> *@
        @* </p> *@
      </div>
        <div id="trivia" class="callOut">
            <h1>Did You Know?</h1>
            <p>California produces over 17 million gallons of wine each year!</p>
        </div>
    </aside>
  </div>
  <footer id="pageFooter">
  <section id="quickLinks">
  <h1>Quick Nav</h1>
    <ul id="quickNav">
      <li><a href="/" title="Our home page">Home</a></li>
      <li><a href="/tours.htm" title="Explore our tours">Tours</a></li>
      <li><a href="mission.htm" title="What we think">Mission</a></li>
      <li><a href="resources.htm" title="Guidance and planning">Resources</a></li>
      <li><a href="explorers.htm" title="Join our community">Explorers</a></li>
      <li><a href="contact.htm" title="Contact and support">Contact</a></li>
    </ul>
  </section>
  <section id="footerResources">
  <h1>Resources</h1>
  <ul id="quickNav">
    <li><a href="resources/faq.htm" title="Our home page">FAQ</a></li>
    <li><a href="support.htm" title="Need help?">Support</a></li>
    <li><a href="resources/legal.htm" title="The fine print">Legal</a></li><li><a href="login.htm">Login</a></li>
  </ul>
  <p>
    Copyright Chris Elbert @DateTime.Now.Year
  </p>
  </section>
  <section id="companyInfo">
  <h1>Contact</h1>
  <h2>Explore California</h2>
      <p>5605 Nota Street<br />
        Ventura, CA 93003</p>
      <p>866.555.4310<br />866.555.4315 <em>(24 hour support)</em></p>
  </section>
  </footer>
</div>
</body>
</html>

ExploreCalifornia/Views/Shared/_Post.cshtml
@inject FormattingService Format
@using ExploreCalifornia.Models
@model ExploreCalifornia.Models.Post


<article class="blog-post">
    <h1>
        @Html.ActionLink(Model.Title, "Post", "Blog", new { year = Model.Posted.Year, month = Model.Posted.Month, id = Model.Id })
    </h1>
    <div class="details">
        Posted <span>@Format.AsFormattedDate(Model.Posted)</span> by <span>@Model.Author</span>
    </div>
    <div class="content">
        @Model.Body
    </div>
</article>